'use client';
import { useEffect, useRef, useState } from 'react';

type Props={onSelect:(rank:number)=>void};
const billboardNodes=['Plane.029','Plane.031','Plane.032','Plane.036','Cube.004','Cube.008','Cube.026','Cube.027','Cube.028','Cube.101','Plane.037','Cube.007','Cube.030','Cube.031','Cube.033','Cube.034','Cube.035','Cube.036','Cube.043','Cube.044','Cube.045','Cube.046','Cube.047','Cube.056','Cube.057','Cube.063','Cube.078','Cube.114','Cube.117','Cube.080'];
const billboardMaterials=new Set(['Material.039','Material.056','Material.097','Material.020','Material.024','Material.234','Material.017','Material.047','Material.049','Material.054','Material.155','Material.082','Material.093','Material.212','filename-dsc00084-jpg','Material.281','Material.119','Material.142','Material.230','Material.263','Material.269']);
const featured=[['VOIDLABS','THE FUTURE IS YOURS','#071b52','#62b8ff'],['AURORA','MAKE YOUR OWN LIGHT','#421465','#ff78e8'],['KINETIC','MOVE DIFFERENT','#cdeb34','#111111'],['NOVA.FM','HEAR THE UNHEARD','#76183f','#ff75aa'],['PIXEL.FUN','PLAY FOREVER','#9e234d','#ffc240']] as const;

export default function BabylonSquare({onSelect}:Props){const canvas=useRef<HTMLCanvasElement>(null);const pressed=useRef(new Set<number>());const [status,setStatus]=useState('Loading the Square…');const sendKey=(code:number,type:'keydown'|'keyup')=>{if(!canvas.current)return;const event=new KeyboardEvent(type,{bubbles:true});Object.defineProperty(event,'keyCode',{value:code});canvas.current.dispatchEvent(event)};const setMove=(next:number[])=>{const wanted=new Set(next);pressed.current.forEach(code=>{if(!wanted.has(code)){sendKey(code,'keyup');pressed.current.delete(code)}});wanted.forEach(code=>{if(!pressed.current.has(code)){sendKey(code,'keydown');pressed.current.add(code)}})};const moveJoystick=(e:React.PointerEvent<HTMLDivElement>)=>{if(!e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.setPointerCapture(e.pointerId);const rect=e.currentTarget.getBoundingClientRect(),rawX=e.clientX-(rect.left+rect.width/2),rawY=e.clientY-(rect.top+rect.height/2),distance=Math.hypot(rawX,rawY),limit=38,scale=distance>limit?limit/distance:1,x=rawX*scale,y=rawY*scale;(e.currentTarget.querySelector('.joystick-knob') as HTMLElement).style.transform=`translate(${x}px,${y}px)`;const keys:number[]=[];if(y<-9)keys.push(38);if(y>9)keys.push(40);if(x<-9)keys.push(37);if(x>9)keys.push(39);setMove(keys)};const stopJoystick=(e:React.PointerEvent<HTMLDivElement>)=>{setMove([]);const knob=e.currentTarget.querySelector('.joystick-knob') as HTMLElement;if(knob)knob.style.transform='translate(0,0)'};useEffect(()=>{let disposed=false;let cleanup=()=>{};(async()=>{
  const B=await import('@babylonjs/core');await import('@babylonjs/loaders/glTF');if(disposed||!canvas.current)return;
  const mobile=window.matchMedia('(max-width: 850px)').matches;const engine=new B.Engine(canvas.current,true,{preserveDrawingBuffer:false,stencil:false,adaptToDeviceRatio:true});engine.setHardwareScalingLevel(mobile?1.2:window.devicePixelRatio>1.5?1.5:1);
  const scene=new B.Scene(engine);scene.fogMode=B.Scene.FOGMODE_EXP2;scene.collisionsEnabled=true;
  const camera=new B.UniversalCamera('streetCamera',B.Vector3.Zero(),scene);camera.minZ=.04;camera.inertia=.68;camera.angularSensibility=3200;camera.checkCollisions=true;camera.keysUp=[87,38];camera.keysDown=[83,40];camera.keysLeft=[65,37];camera.keysRight=[68,39];camera.attachControl(canvas.current,true);const surface=canvas.current;let lookPointer:number|null=null,lastLookX=0,lastLookY=0;const beginLook=(event:PointerEvent)=>{if(!mobile||event.pointerType==='mouse')return;lookPointer=event.pointerId;lastLookX=event.clientX;lastLookY=event.clientY;surface.setPointerCapture(event.pointerId);event.preventDefault()};const moveLook=(event:PointerEvent)=>{if(event.pointerId!==lookPointer)return;const dx=event.clientX-lastLookX,dy=event.clientY-lastLookY;lastLookX=event.clientX;lastLookY=event.clientY;camera.rotation.y+=dx*.0065;camera.rotation.x=Math.max(-.58,Math.min(.38,camera.rotation.x+dy*.0045));event.preventDefault()};const endLook=(event:PointerEvent)=>{if(event.pointerId===lookPointer)lookPointer=null};if(mobile){camera.inputs.removeByType('FreeCameraTouchInput');surface.addEventListener('pointerdown',beginLook,{passive:false});surface.addEventListener('pointermove',moveLook,{passive:false});surface.addEventListener('pointerup',endLook);surface.addEventListener('pointercancel',endLook);surface.dataset.touchLook='enabled'}
  const hemi=new B.HemisphericLight('nycAmbient',new B.Vector3(0,1,0),scene);const sun=new B.DirectionalLight('nycSun',new B.Vector3(-.45,-1,.3),scene);sun.specular=new B.Color3(.8,.78,.7);
  const glow=new B.GlowLayer('billboardGlow',scene,{blurKernelSize:22});glow.intensity=.35;
  const nycClock=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hour:'numeric',minute:'numeric',second:'numeric',hourCycle:'h23'});const color=(hex:string)=>B.Color3.FromHexString(hex);const lightingStops=[
    {hour:0,sky:'#030711',fog:'#07101d',ambient:'#5875a3',ground:'#120d1c',sun:'#768bb0',hemi:.42,sunPower:.05,glow:.72,exposure:.92},
    {hour:5,sky:'#101629',fog:'#172237',ambient:'#7185a8',ground:'#201727',sun:'#9ba7bb',hemi:.52,sunPower:.12,glow:.6,exposure:.96},
    {hour:7,sky:'#e48770',fog:'#b98274',ambient:'#ffd0aa',ground:'#5c4037',sun:'#ffb36b',hemi:.82,sunPower:1.25,glow:.34,exposure:1.02},
    {hour:10,sky:'#65a9d8',fog:'#8ebbd2',ambient:'#dbeeff',ground:'#6d756c',sun:'#fff0ce',hemi:1.02,sunPower:1.85,glow:.18,exposure:1.06},
    {hour:16,sky:'#5598ca',fog:'#80afc7',ambient:'#d8ebfa',ground:'#747568',sun:'#fff1d2',hemi:1,sunPower:1.7,glow:.2,exposure:1.05},
    {hour:19,sky:'#d9684d',fog:'#9f665e',ambient:'#ffc095',ground:'#4d3237',sun:'#ff8b4b',hemi:.76,sunPower:.9,glow:.42,exposure:1},
    {hour:21,sky:'#071020',fog:'#0c1829',ambient:'#6684ad',ground:'#17101f',sun:'#8298bb',hemi:.48,sunPower:.08,glow:.68,exposure:.94},
    {hour:24,sky:'#030711',fog:'#07101d',ambient:'#5875a3',ground:'#120d1c',sun:'#768bb0',hemi:.42,sunPower:.05,glow:.72,exposure:.92}
  ];const applyNycLighting=()=>{const parts=Object.fromEntries(nycClock.formatToParts(new Date()).filter(part=>part.type!=='literal').map(part=>[part.type,Number(part.value)]));const hour=parts.hour+parts.minute/60+parts.second/3600;let from=lightingStops[0],to=lightingStops[1];for(let i=0;i<lightingStops.length-1;i++){if(hour>=lightingStops[i].hour&&hour<=lightingStops[i+1].hour){from=lightingStops[i];to=lightingStops[i+1];break}}const progress=(hour-from.hour)/(to.hour-from.hour);const mix=(a:number,b:number)=>a+(b-a)*progress;const mixColor=(a:string,b:string)=>B.Color3.Lerp(color(a),color(b),progress);const sky=mixColor(from.sky,to.sky),fog=mixColor(from.fog,to.fog),billboardGlow=mix(from.glow,to.glow);scene.clearColor=new B.Color4(sky.r,sky.g,sky.b,1);scene.fogColor=fog;scene.fogDensity=.00135+billboardGlow*.00225;hemi.diffuse=mixColor(from.ambient,to.ambient);hemi.groundColor=mixColor(from.ground,to.ground);hemi.intensity=mix(from.hemi,to.hemi);sun.diffuse=mixColor(from.sun,to.sun);sun.intensity=mix(from.sunPower,to.sunPower);glow.intensity=billboardGlow;scene.imageProcessingConfiguration.exposure=mix(from.exposure,to.exposure);scene.imageProcessingConfiguration.contrast=1.08;const angle=((hour-6)/24)*Math.PI*2;sun.direction.set(Math.cos(angle)*-.65,-Math.max(.08,Math.sin(angle)),Math.sin(angle)*.45)};applyNycLighting();const lightingTimer=window.setInterval(applyNycLighting,60_000);
  try{
    const imported=await B.SceneLoader.ImportMeshAsync('', '/models/', mobile?'timesquare-mobile.glb':'timesquare-web.glb', scene);if(disposed)return;const findImported=(name:string)=>imported.meshes.find(mesh=>mesh.name===name||mesh.id===name||mesh.name.startsWith(`${name}_`)||mesh.id.startsWith(`${name}_`));
    const roots=imported.meshes.filter(m=>!m.parent);const vectors=roots.length?roots[0].getHierarchyBoundingVectors(true):scene.getWorldExtends();const center=vectors.min.add(vectors.max).scale(.5);const extent=vectors.max.subtract(vectors.min);const radius=Math.max(extent.x,extent.y,extent.z);
    const eyeY=vectors.min.y+extent.y*.021;const marginX=extent.x*.055;const marginZ=extent.z*.12;const bodyWidth=Math.max(extent.x,extent.z)*.00115;const bodyHeight=extent.y*.0065;
    camera.position.set(center.x,eyeY,center.z);camera.speed=Math.max(.08,radius*.0038);
    camera.ellipsoid.set(bodyWidth,bodyHeight,bodyWidth);camera.ellipsoidOffset.set(0,-bodyHeight*.78,0);
    imported.meshes.forEach(mesh=>{if(!(mesh instanceof B.Mesh)||mesh.getTotalVertices()===0)return;const size=mesh.getBoundingInfo().boundingBox.maximumWorld.subtract(mesh.getBoundingInfo().boundingBox.minimumWorld);const name=mesh.name.toLowerCase();const walkSurface=/road|street|ground|sidewalk|crosswalk|zebra|asphalt/.test(name);const solidEnough=size.y>bodyHeight*.55&&Math.max(size.x,size.z)>bodyWidth*.2;if(!walkSurface&&solidEnough){mesh.checkCollisions=true;mesh.useOctreeForCollisions=true}});scene.createOrUpdateSelectionOctree(64,2);
    const area=(mesh:B.AbstractMesh)=>{const box=mesh.getBoundingInfo().boundingBox;const size=box.maximumWorld.subtract(box.minimumWorld);return Math.max(size.x*size.y,size.x*size.z,size.y*size.z)};
    const namedCandidates=billboardNodes.map(findImported).filter((mesh):mesh is B.AbstractMesh=>Boolean(mesh));const materialCandidates=imported.meshes.filter(mesh=>{const material=(mesh as B.Mesh).material;if(!material)return false;const names=[material.name,...(('subMaterials' in material)?(material.subMaterials||[]).map(item=>item?.name||''):[])];return names.some(name=>billboardMaterials.has(name))});const candidates=(namedCandidates.length>=20?namedCandidates:materialCandidates).filter((mesh,index,list)=>list.indexOf(mesh)===index).sort((a,b)=>area(b)-area(a)).slice(0,30);
    const topFive=candidates.slice(0,5);const topCenter=topFive.reduce((sum,mesh)=>sum.add(mesh.getBoundingInfo().boundingBox.centerWorld),B.Vector3.Zero()).scale(1/Math.max(1,topFive.length));camera.setTarget(new B.Vector3(topCenter.x,Math.max(eyeY+extent.y*.07,topCenter.y),topCenter.z));
    topFive.forEach((mesh,index)=>{const [name,tag,bg,fg]=featured[index];mesh.metadata={...(mesh.metadata||{}),rank:index+1};mesh.isPickable=true;
      const tex=new B.DynamicTexture(`featured_${index+1}`,{width:1024,height:512},scene,false);const ctx=tex.getContext();ctx.fillStyle=bg;ctx.fillRect(0,0,1024,512);ctx.strokeStyle=fg;ctx.lineWidth=18;ctx.strokeRect(18,18,988,476);ctx.fillStyle=fg;ctx.textAlign='right';ctx.font='900 105px Arial';ctx.fillText(`#${index+1}`,955,125);ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font='900 120px Arial';ctx.fillText(name,512,310);ctx.font='bold 28px monospace';ctx.fillText(tag,512,385);ctx.fillStyle=fg;ctx.font='900 30px monospace';ctx.fillText('CLICK TO OUTBID',512,450);tex.update();const bm=new B.StandardMaterial(`featured_material_${index+1}`,scene);bm.diffuseTexture=tex;bm.emissiveTexture=tex;bm.emissiveColor=B.Color3.White();bm.disableLighting=true;bm.backFaceCulling=false;mesh.material=bm;
    });
    candidates.slice(5).forEach((mesh,index)=>{const rank=index+6;mesh.metadata={...(mesh.metadata||{}),rank};mesh.isPickable=true;const hue=(rank*37)%360;const tex=new B.DynamicTexture(`ranked_billboard_${rank}`,{width:1024,height:512},scene,false);const ctx=tex.getContext();ctx.fillStyle=`hsl(${hue} 55% 18%)`;ctx.fillRect(0,0,1024,512);ctx.strokeStyle='#d7ff35';ctx.lineWidth=18;ctx.strokeRect(18,18,988,476);ctx.fillStyle='#d7ff35';ctx.textAlign='right';ctx.font='900 105px Arial';ctx.fillText(`#${rank}`,955,125);ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font='900 76px Arial';ctx.fillText('TIMESQUARES.LOL',512,310);ctx.fillStyle='#d7ff35';ctx.font='900 32px monospace';ctx.fillText('CLICK TO OUTBID',512,425);tex.update();const mat=new B.StandardMaterial(`ranked_material_${rank}`,scene);mat.diffuseTexture=tex;mat.emissiveTexture=tex;mat.disableLighting=true;mat.backFaceCulling=false;mesh.material=mat;});
    const yearParts=['Cube.082','Cube.083','Cube.084','Cube.085','Cube.086','Cube.087'].map(findImported).filter((mesh):mesh is B.AbstractMesh=>Boolean(mesh));const yearAnchor=yearParts[0];if(yearAnchor){const box=yearAnchor.getBoundingInfo().boundingBox;const size=box.maximumWorld.subtract(box.minimumWorld);const yearSign=B.MeshBuilder.CreatePlane('year_2026',{width:Math.max(size.x,size.z)*1.06,height:size.y*1.06,sideOrientation:B.Mesh.DOUBLESIDE},scene);yearSign.position.copyFrom(box.centerWorld);yearSign.rotationQuaternion=yearAnchor.absoluteRotationQuaternion?.clone()||B.Quaternion.Identity();yearSign.isPickable=false;yearParts.forEach(mesh=>mesh.setEnabled(false));const yearTex=new B.DynamicTexture('year_2026_texture',{width:512,height:768},scene,false);const yearCtx=yearTex.getContext();yearCtx.fillStyle='#101417';yearCtx.fillRect(0,0,512,768);yearCtx.strokeStyle='#ff4d2e';yearCtx.lineWidth=22;yearCtx.strokeRect(12,12,488,744);yearCtx.fillStyle='#ff4d2e';yearCtx.textAlign='center';yearCtx.font='900 150px Arial';yearCtx.fillText('2026',256,440);yearTex.update();const yearMat=new B.StandardMaterial('year_2026_material',scene);yearMat.diffuseTexture=yearTex;yearMat.emissiveTexture=yearTex;yearMat.disableLighting=true;yearMat.backFaceCulling=false;yearSign.material=yearMat;}
    scene.onBeforeRenderObservable.add(()=>{camera.position.x=Math.min(vectors.max.x-marginX,Math.max(vectors.min.x+marginX,camera.position.x));camera.position.z=Math.min(vectors.max.z-marginZ,Math.max(vectors.min.z+marginZ,camera.position.z));camera.position.y=eyeY;camera.cameraDirection.y=0;});
    scene.onPointerObservable.add(info=>{if(info.type===B.PointerEventTypes.POINTERPICK){let mesh=info.pickInfo?.pickedMesh;while(mesh&&!mesh.metadata?.rank)mesh=mesh.parent as B.AbstractMesh|null;if(mesh?.metadata?.rank)onSelect(mesh.metadata.rank)}});
    setStatus('');
  }catch(error){console.error(error);setStatus('3D scene unavailable — open the leaderboard');}
  engine.runRenderLoop(()=>scene.render());const resize=()=>engine.resize();window.addEventListener('resize',resize);cleanup=()=>{window.clearInterval(lightingTimer);window.removeEventListener('resize',resize);surface.removeEventListener('pointerdown',beginLook);surface.removeEventListener('pointermove',moveLook);surface.removeEventListener('pointerup',endLook);surface.removeEventListener('pointercancel',endLook);scene.dispose();engine.dispose()};
  })();return()=>{disposed=true;cleanup()};},[onSelect]);return <div className="babylon-stage"><canvas ref={canvas} className="babylon-canvas" aria-label="Interactive 3D Times Square billboard leaderboard"/><div className="mobile-joystick" role="group" aria-label="Walking joystick" onPointerDown={moveJoystick} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))moveJoystick(e)}} onPointerUp={stopJoystick} onPointerCancel={stopJoystick}><div className="joystick-ring"><div className="joystick-knob"/></div><span>MOVE</span></div><div className="mobile-look-hint">DRAG HERE TO TURN</div>{status&&<div className="scene-loading" role="status"><div className="load-skyline"><i/><i/><i/><i/><i/></div><strong>TIMESQUARES<span>.LOL</span></strong><small>{status}</small><em>30 LIVE BILLBOARDS · ENTERING BROADWAY</em></div>}</div>}
