'use client';
import { useEffect, useRef, useState } from 'react';

type Props={onSelect:(rank:number)=>void};
const billboardNodes=['Plane.029','Plane.031','Plane.032','Plane.036','Cube.004','Cube.008','Cube.026','Cube.027','Cube.028','Cube.101','Plane.037','Cube.007','Cube.030','Cube.031','Cube.033','Cube.034','Cube.035','Cube.036','Cube.043','Cube.044','Cube.045','Cube.046','Cube.047','Cube.056','Cube.057','Cube.063','Cube.078','Cube.114','Cube.117','Cube.080'];
const billboardMaterials=new Set(['Material.039','Material.056','Material.097','Material.020','Material.024','Material.234','Material.017','Material.047','Material.049','Material.054','Material.155','Material.082','Material.093','Material.212','filename-dsc00084-jpg','Material.281','Material.119','Material.142','Material.230','Material.263','Material.269']);
const featured=[['VOIDLABS','THE FUTURE IS YOURS','#071b52','#62b8ff'],['AURORA','MAKE YOUR OWN LIGHT','#421465','#ff78e8'],['KINETIC','MOVE DIFFERENT','#cdeb34','#111111'],['NOVA.FM','HEAR THE UNHEARD','#76183f','#ff75aa'],['PIXEL.FUN','PLAY FOREVER','#9e234d','#ffc240']] as const;

export default function BabylonSquare({onSelect}:Props){const canvas=useRef<HTMLCanvasElement>(null);const pressed=useRef(new Set<number>());const [ready,setReady]=useState(false);const [failed,setFailed]=useState(false);const sendKey=(code:number,type:'keydown'|'keyup')=>{if(!canvas.current)return;const event=new KeyboardEvent(type,{bubbles:true});Object.defineProperty(event,'keyCode',{value:code});canvas.current.dispatchEvent(event)};const setMove=(next:number[])=>{const wanted=new Set(next);pressed.current.forEach(code=>{if(!wanted.has(code)){sendKey(code,'keyup');pressed.current.delete(code)}});wanted.forEach(code=>{if(!pressed.current.has(code)){sendKey(code,'keydown');pressed.current.add(code)}})};const moveJoystick=(e:React.PointerEvent<HTMLDivElement>)=>{if(!e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.setPointerCapture(e.pointerId);const rect=e.currentTarget.getBoundingClientRect(),rawX=e.clientX-(rect.left+rect.width/2),rawY=e.clientY-(rect.top+rect.height/2),distance=Math.hypot(rawX,rawY),limit=38,scale=distance>limit?limit/distance:1,x=rawX*scale,y=rawY*scale;(e.currentTarget.querySelector('.joystick-knob') as HTMLElement).style.transform=`translate(${x}px,${y}px)`;const keys:number[]=[];if(y<-9)keys.push(38);if(y>9)keys.push(40);if(x<-9)keys.push(37);if(x>9)keys.push(39);setMove(keys)};const stopJoystick=(e:React.PointerEvent<HTMLDivElement>)=>{setMove([]);const knob=e.currentTarget.querySelector('.joystick-knob') as HTMLElement;if(knob)knob.style.transform='translate(0,0)'};useEffect(()=>{let disposed=false;let cleanup=()=>{};(async()=>{
  const B=await import('@babylonjs/core');await import('@babylonjs/loaders/glTF');if(disposed||!canvas.current)return;
  const mobile=window.matchMedia('(max-width: 850px)').matches;const engine=new B.Engine(canvas.current,true,{preserveDrawingBuffer:false,stencil:false,adaptToDeviceRatio:true});engine.setHardwareScalingLevel(mobile?1.2:window.devicePixelRatio>1.5?1.5:1);
  const scene=new B.Scene(engine);scene.fogMode=B.Scene.FOGMODE_EXP2;scene.collisionsEnabled=true;
  const camera=new B.UniversalCamera('streetCamera',B.Vector3.Zero(),scene);camera.minZ=.04;camera.inertia=.68;camera.angularSensibility=3200;camera.checkCollisions=true;camera.keysUp=[87,38];camera.keysDown=[83,40];camera.keysLeft=[65,37];camera.keysRight=[68,39];camera.attachControl(canvas.current,true);const surface=canvas.current;let lookPointer:number|null=null,lastLookX=0,lastLookY=0,lastSelection=0;const beginLook=(event:PointerEvent)=>{if(!mobile||event.pointerType==='mouse')return;lookPointer=event.pointerId;lastLookX=event.clientX;lastLookY=event.clientY;surface.setPointerCapture(event.pointerId);event.preventDefault()};const moveLook=(event:PointerEvent)=>{if(event.pointerId!==lookPointer)return;const dx=event.clientX-lastLookX,dy=event.clientY-lastLookY;lastLookX=event.clientX;lastLookY=event.clientY;camera.rotation.y+=dx*.0065;camera.rotation.x=Math.max(-.58,Math.min(.38,camera.rotation.x+dy*.0045));event.preventDefault()};const clickFallback=()=>{};const endLook=(event:PointerEvent)=>{if(event.pointerId===lookPointer)lookPointer=null};surface.addEventListener('pointerdown',beginLook,{passive:false,capture:true});surface.addEventListener('pointerup',endLook,{capture:true});surface.addEventListener('pointercancel',endLook,{capture:true});if(mobile){camera.inputs.removeByType('FreeCameraTouchInput');surface.addEventListener('pointermove',moveLook,{passive:false});surface.dataset.touchLook='enabled'}
  const hemi=new B.HemisphericLight('nycAmbient',new B.Vector3(0,1,0),scene);const sun=new B.DirectionalLight('nycSun',new B.Vector3(-.45,-1,.3),scene);sun.specular=new B.Color3(.8,.78,.7);
  const glow=new B.GlowLayer('billboardGlow',scene,{blurKernelSize:22});glow.intensity=.35;
  const nycClock=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hour:'numeric',minute:'numeric',second:'numeric',hourCycle:'h23'});const color=(hex:string)=>B.Color3.FromHexString(hex);const lightingStops=[
    {hour:0,sky:'#030711',fog:'#07101d',ambient:'#5875a3',ground:'#120d1c',sun:'#768bb0',hemi:.42,sunPower:.05,glow:.55,emission:.9,exposure:.92},
    {hour:5,sky:'#0c1322',fog:'#172033',ambient:'#7185a8',ground:'#201727',sun:'#9ba7bb',hemi:.5,sunPower:.1,glow:.48,emission:.78,exposure:.94},
    {hour:7,sky:'#826876',fog:'#766d78',ambient:'#d8b8a4',ground:'#493b3d',sun:'#e9ac7b',hemi:.68,sunPower:.62,glow:.18,emission:.45,exposure:.94},
    {hour:10,sky:'#659ac0',fog:'#8daab9',ambient:'#d4e2e9',ground:'#687069',sun:'#f2e5cb',hemi:.88,sunPower:1.2,glow:.1,emission:.32,exposure:.98},
    {hour:16,sky:'#568db5',fog:'#7f9da9',ambient:'#d3e0e7',ground:'#6c7067',sun:'#f4e6cf',hemi:.88,sunPower:1.12,glow:.11,emission:.34,exposure:.98},
    {hour:18,sky:'#667f99',fog:'#77848d',ambient:'#c2c8c8',ground:'#555b58',sun:'#dfcfbd',hemi:.74,sunPower:.68,glow:.13,emission:.38,exposure:.95},
    {hour:19.5,sky:'#4b5163',fog:'#555b66',ambient:'#a6a7ad',ground:'#3c3d42',sun:'#c8b4a6',hemi:.59,sunPower:.28,glow:.19,emission:.46,exposure:.92},
    {hour:20.5,sky:'#172237',fog:'#263140',ambient:'#788aa1',ground:'#25242b',sun:'#9b9eaa',hemi:.5,sunPower:.1,glow:.37,emission:.68,exposure:.91},
    {hour:21,sky:'#071020',fog:'#0c1829',ambient:'#6684ad',ground:'#17101f',sun:'#8298bb',hemi:.48,sunPower:.08,glow:.52,emission:.84,exposure:.92},
    {hour:24,sky:'#030711',fog:'#07101d',ambient:'#5875a3',ground:'#120d1c',sun:'#768bb0',hemi:.42,sunPower:.05,glow:.55,emission:.9,exposure:.92}
  ];const applyNycLighting=()=>{const parts=Object.fromEntries(nycClock.formatToParts(new Date()).filter(part=>part.type!=='literal').map(part=>[part.type,Number(part.value)]));const hour=parts.hour+parts.minute/60+parts.second/3600;let from=lightingStops[0],to=lightingStops[1];for(let i=0;i<lightingStops.length-1;i++){if(hour>=lightingStops[i].hour&&hour<=lightingStops[i+1].hour){from=lightingStops[i];to=lightingStops[i+1];break}}const progress=(hour-from.hour)/(to.hour-from.hour);const mix=(a:number,b:number)=>a+(b-a)*progress;const mixColor=(a:string,b:string)=>B.Color3.Lerp(color(a),color(b),progress);const sky=mixColor(from.sky,to.sky),fog=mixColor(from.fog,to.fog),billboardGlow=mix(from.glow,to.glow),emission=mix(from.emission,to.emission);scene.clearColor=new B.Color4(sky.r,sky.g,sky.b,1);scene.fogColor=fog;scene.fogDensity=.00115+billboardGlow*.0017;hemi.diffuse=mixColor(from.ambient,to.ambient);hemi.groundColor=mixColor(from.ground,to.ground);hemi.intensity=mix(from.hemi,to.hemi);sun.diffuse=mixColor(from.sun,to.sun);sun.intensity=mix(from.sunPower,to.sunPower);glow.intensity=billboardGlow;scene.imageProcessingConfiguration.exposure=mix(from.exposure,to.exposure);scene.imageProcessingConfiguration.contrast=1.04;scene.materials.forEach(material=>{if((material.name.startsWith('featured_material_')||material.name.startsWith('ranked_material_'))&&material instanceof B.StandardMaterial)material.emissiveColor.set(emission,emission,emission)});const angle=((hour-6)/24)*Math.PI*2;sun.direction.set(Math.cos(angle)*-.65,-Math.max(.08,Math.sin(angle)),Math.sin(angle)*.45)};applyNycLighting();const lightingTimer=window.setInterval(applyNycLighting,60_000);
  try{
    const imported=await B.SceneLoader.ImportMeshAsync('', '/models/', mobile?'timesquare-mobile.glb':'timesquare-web.glb', scene);if(disposed)return;const findImported=(name:string)=>imported.meshes.find(mesh=>mesh.name===name||mesh.id===name||mesh.name.startsWith(`${name}_`)||mesh.id.startsWith(`${name}_`));
    const roots=imported.meshes.filter(m=>!m.parent);const vectors=roots.length?roots[0].getHierarchyBoundingVectors(true):scene.getWorldExtends();const center=vectors.min.add(vectors.max).scale(.5);const extent=vectors.max.subtract(vectors.min);const radius=Math.max(extent.x,extent.y,extent.z);
    const eyeY=vectors.min.y+extent.y*.021;const marginX=extent.x*.055;const marginZ=extent.z*.12;const bodyWidth=Math.max(extent.x,extent.z)*.00115;const bodyHeight=extent.y*.0065;
    camera.position.set(center.x,eyeY,center.z);camera.speed=Math.max(.08,radius*.0038);
    camera.ellipsoid.set(bodyWidth,bodyHeight,bodyWidth);camera.ellipsoidOffset.set(0,-bodyHeight*.78,0);
    imported.meshes.forEach(mesh=>{if(!(mesh instanceof B.Mesh)||mesh.getTotalVertices()===0)return;const size=mesh.getBoundingInfo().boundingBox.maximumWorld.subtract(mesh.getBoundingInfo().boundingBox.minimumWorld);const name=mesh.name.toLowerCase();const walkSurface=/road|street|ground|sidewalk|crosswalk|zebra|asphalt/.test(name);const solidEnough=size.y>bodyHeight*.55&&Math.max(size.x,size.z)>bodyWidth*.2;if(!walkSurface&&solidEnough){mesh.checkCollisions=true;mesh.useOctreeForCollisions=true}});scene.createOrUpdateSelectionOctree(64,2);
    const area=(mesh:B.AbstractMesh)=>{const box=mesh.getBoundingInfo().boundingBox;const size=box.maximumWorld.subtract(box.minimumWorld);return Math.max(size.x*size.y,size.x*size.z,size.y*size.z)};
    const hasBillboardMaterial=(mesh:B.AbstractMesh)=>Boolean(mesh.material)&&[mesh.material?.name,...(mesh.material instanceof B.MultiMaterial?(mesh.material.subMaterials||[]).map(item=>item?.name||''):[])].some(name=>billboardMaterials.has(name));type BillboardTarget={mesh:InstanceType<typeof B.Mesh>,materialIndex:number,subMeshIds:number[],surfaces:B.AbstractMesh[]};const targets=billboardNodes.map(name=>{const root=imported.transformNodes.find(node=>node.name===name)||imported.meshes.find(mesh=>mesh.name===name),surfaces=(root?.getChildMeshes(false)||imported.meshes.filter(mesh=>mesh.name.startsWith(`${name}_primitive`))).filter(hasBillboardMaterial);if(!surfaces.length)return null;const first=surfaces[0],mesh=first instanceof B.InstancedMesh?first.sourceMesh:first;if(!(mesh instanceof B.Mesh))return null;const subMeshIds=mesh.subMeshes.map((_,index)=>index),materialIndex=mesh.subMeshes[0]?.materialIndex||0;return{mesh,materialIndex,subMeshIds,surfaces}}).filter((target):target is BillboardTarget=>Boolean(target));
    const corridorTarget=new B.Vector3(camera.position.x+extent.x,eyeY+extent.y*.07,camera.position.z),viewDirection=corridorTarget.subtract(camera.position).normalize();camera.setTarget(corridorTarget);const visibility=(target:BillboardTarget)=>{const box=target.mesh.subMeshes[target.subMeshIds[0]]?.getBoundingInfo().boundingBox||target.mesh.getBoundingInfo().boundingBox,size=box.maximumWorld.subtract(box.minimumWorld),center=box.centerWorld,toScreen=center.subtract(camera.position),distance=Math.max(.001,toScreen.length()),alignment=Math.max(.05,B.Vector3.Dot(toScreen.normalize(),viewDirection)),surfaceArea=Math.max(size.x*size.y,size.x*size.z,size.y*size.z);return surfaceArea/(distance*distance)*alignment**4};targets.sort((a,b)=>visibility(b)-visibility(a));targets.forEach((target,index)=>{const rank=index+1,mesh=target.mesh;mesh.metadata={...(mesh.metadata||{}),rankBySubMesh:{...(mesh.metadata?.rankBySubMesh||{})},rankByMaterial:{...(mesh.metadata?.rankByMaterial||{})}};mesh.subMeshes.forEach((subMesh,id)=>{if(mesh.metadata.rankBySubMesh[id])return;mesh.metadata.rankBySubMesh[id]=rank;mesh.metadata.rankBySubMesh[(subMesh as any)._id]=rank})});const topFive=targets.slice(0,5);
    topFive.forEach((target,index)=>{const mesh=target.mesh,[name,tag,bg,fg]=featured[index],rank=index+1;mesh.metadata={...(mesh.metadata||{}),rankBySubMesh:{...(mesh.metadata?.rankBySubMesh||{})},rankByMaterial:{...(mesh.metadata?.rankByMaterial||{}),[target.materialIndex]:rank}};target.subMeshIds.forEach(id=>{mesh.metadata.rankBySubMesh[id]=rank;mesh.metadata.rankBySubMesh[(mesh.subMeshes[id] as any)?._id]=rank});mesh.isPickable=true;
      const tex=new B.DynamicTexture(`featured_${rank}`,{width:1024,height:512},scene,false);const ctx=tex.getContext();ctx.fillStyle=bg;ctx.fillRect(0,0,1024,512);ctx.strokeStyle=fg;ctx.lineWidth=18;ctx.strokeRect(18,18,988,476);ctx.fillStyle=fg;ctx.textAlign='right';ctx.font='900 105px Arial';ctx.fillText(`#${rank}`,955,125);ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font='900 120px Arial';ctx.fillText(name,512,310);ctx.font='bold 28px monospace';ctx.fillText(tag,512,385);ctx.fillStyle=fg;ctx.font='900 30px monospace';ctx.fillText('CLICK TO OUTBID',512,450);tex.update();const bm=new B.StandardMaterial(`featured_material_${rank}`,scene);bm.diffuseTexture=tex;bm.emissiveTexture=tex;bm.emissiveColor=B.Color3.White();bm.disableLighting=true;bm.backFaceCulling=false;if(mesh.material instanceof B.MultiMaterial)mesh.material.subMaterials[target.materialIndex]=bm;else mesh.material=bm;
    });
    targets.slice(5).forEach((target,index)=>{const mesh=target.mesh,rank=index%25+6;mesh.metadata={...(mesh.metadata||{}),rankBySubMesh:{...(mesh.metadata?.rankBySubMesh||{})},rankByMaterial:{...(mesh.metadata?.rankByMaterial||{}),[target.materialIndex]:rank}};target.subMeshIds.forEach(id=>{mesh.metadata.rankBySubMesh[id]=rank;mesh.metadata.rankBySubMesh[(mesh.subMeshes[id] as any)?._id]=rank});mesh.isPickable=true;const hue=(rank*37)%360;const tex=new B.DynamicTexture(`ranked_billboard_${rank}_${index}`,{width:1024,height:512},scene,false);const ctx=tex.getContext();ctx.fillStyle=`hsl(${hue} 55% 18%)`;ctx.fillRect(0,0,1024,512);ctx.strokeStyle='#d7ff35';ctx.lineWidth=18;ctx.strokeRect(18,18,988,476);ctx.fillStyle='#d7ff35';ctx.textAlign='right';ctx.font='900 105px Arial';ctx.fillText(`#${rank}`,955,125);ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font='900 76px Arial';ctx.fillText('TIMESQUARES.LOL',512,310);ctx.fillStyle='#d7ff35';ctx.font='900 32px monospace';ctx.fillText('CLICK TO OUTBID',512,425);tex.update();const mat=new B.StandardMaterial(`ranked_material_${rank}_${index}`,scene);mat.diffuseTexture=tex;mat.emissiveTexture=tex;mat.disableLighting=true;mat.backFaceCulling=false;if(mesh.material instanceof B.MultiMaterial)mesh.material.subMaterials[target.materialIndex]=mat;else mesh.material=mat;});scene.onPointerObservable.add(pointerInfo=>{if(pointerInfo.type!==B.PointerEventTypes.POINTERDOWN)return;const hit=pointerInfo.pickInfo,mesh=hit?.pickedMesh,subMesh=mesh&&(mesh.subMeshes[hit?.subMeshId??-1]||mesh.subMeshes.find(item=>(item as any)._id===hit?.subMeshId)),rank=mesh&&(mesh.metadata?.rankBySubMesh?.[hit?.subMeshId??-1]||mesh.metadata?.rankBySubMesh?.[(subMesh as any)?._id]||mesh.metadata?.rankByMaterial?.[subMesh?.materialIndex]);if(rank&&performance.now()-lastSelection>80){lastSelection=performance.now();onSelect(Number(rank))}},B.PointerEventTypes.POINTERDOWN);applyNycLighting();
    const yearParts=['Cube.082','Cube.083','Cube.084','Cube.085','Cube.086','Cube.087'].map(findImported).filter((mesh):mesh is B.AbstractMesh=>Boolean(mesh));const yearAnchor=yearParts[0];if(yearAnchor){const box=yearAnchor.getBoundingInfo().boundingBox;const size=box.maximumWorld.subtract(box.minimumWorld);const yearSign=B.MeshBuilder.CreatePlane('year_2026',{width:Math.max(size.x,size.z)*1.06,height:size.y*1.06,sideOrientation:B.Mesh.DOUBLESIDE},scene);yearSign.position.copyFrom(box.centerWorld);yearSign.rotationQuaternion=yearAnchor.absoluteRotationQuaternion?.clone()||B.Quaternion.Identity();yearSign.isPickable=false;yearParts.forEach(mesh=>mesh.setEnabled(false));const yearTex=new B.DynamicTexture('year_2026_texture',{width:512,height:768},scene,false);const yearCtx=yearTex.getContext();yearCtx.fillStyle='#101417';yearCtx.fillRect(0,0,512,768);yearCtx.strokeStyle='#ff4d2e';yearCtx.lineWidth=22;yearCtx.strokeRect(12,12,488,744);yearCtx.fillStyle='#ff4d2e';yearCtx.textAlign='center';yearCtx.font='900 150px Arial';yearCtx.fillText('2026',256,440);yearTex.update();const yearMat=new B.StandardMaterial('year_2026_material',scene);yearMat.diffuseTexture=yearTex;yearMat.emissiveTexture=yearTex;yearMat.disableLighting=true;yearMat.backFaceCulling=false;yearSign.material=yearMat;}
    const timeParts=Object.fromEntries(nycClock.formatToParts(new Date()).filter(part=>part.type!=='literal').map(part=>[part.type,Number(part.value)]));const crowdHour=timeParts.hour;const rush=(crowdHour>=7&&crowdHour<=10)||(crowdHour>=16&&crowdHour<=22);const pedestrianCount=mobile?(rush?16:10):(rush?32:20);const humanHeight=extent.y*.016;const groundY=eyeY-humanHeight*.9;const pedestrianColors=['#15191d','#26313b','#4b252a','#273d2b','#493b28','#343044'];const pedestrianMaterials=pedestrianColors.map((hex,index)=>{const material=new B.StandardMaterial(`pedestrian_material_${index}`,scene);material.diffuseColor=color(hex);material.roughness=.95;return material});type Pedestrian={node:any;body:any;head:any;from:any;to:any;progress:number;speed:number;phase:number};const pedestrians:Pedestrian[]=[];
    for(let index=0;index<pedestrianCount;index++){const vertical=index%2===0;const direction=index%4<2?1:-1;const lane=((index%5)-2)*humanHeight*.38;const side=index%3===0?-1:1;const from=vertical?new B.Vector3(center.x+side*extent.x*.045+lane,groundY,center.z-direction*extent.z*.23):new B.Vector3(center.x-direction*extent.x*.19,groundY,center.z+side*extent.z*.038+lane);const to=vertical?new B.Vector3(from.x,groundY,center.z+direction*extent.z*.23):new B.Vector3(center.x+direction*extent.x*.19,groundY,from.z);const node=new B.TransformNode(`pedestrian_${index}`,scene);const body=B.MeshBuilder.CreateCapsule(`pedestrian_body_${index}`,{height:humanHeight*.57,radius:humanHeight*.115,tessellation:8},scene);body.parent=node;body.position.y=humanHeight*.42;body.material=pedestrianMaterials[index%pedestrianMaterials.length];body.isPickable=false;body.checkCollisions=false;const head=B.MeshBuilder.CreateSphere(`pedestrian_head_${index}`,{diameter:humanHeight*.2,segments:8},scene);head.parent=node;head.position.y=humanHeight*.79;head.material=pedestrianMaterials[(index+2)%pedestrianMaterials.length];head.isPickable=false;head.checkCollisions=false;node.rotation.y=Math.atan2(to.x-from.x,to.z-from.z);pedestrians.push({node,body,head,from,to,progress:(index*.173)%1,speed:.035+(index%7)*.004,phase:index*.83})}
    scene.onBeforeRenderObservable.add(()=>{camera.position.x=Math.min(vectors.max.x-marginX,Math.max(vectors.min.x+marginX,camera.position.x));camera.position.z=Math.min(vectors.max.z-marginZ,Math.max(vectors.min.z+marginZ,camera.position.z));camera.position.y=eyeY;camera.cameraDirection.y=0;const seconds=engine.getDeltaTime()/1000;const now=performance.now()*.007;pedestrians.forEach(person=>{person.progress=(person.progress+person.speed*seconds)%1;B.Vector3.LerpToRef(person.from,person.to,person.progress,person.node.position);person.node.position.y=groundY+Math.abs(Math.sin(now+person.phase))*humanHeight*.018;person.body.rotation.z=Math.sin(now+person.phase)*.035;person.head.rotation.y=Math.sin(now*.45+person.phase)*.12})});
    const selectProjectedBillboard=(event:PointerEvent)=>{const rect=surface.getBoundingClientRect(),renderWidth=engine.getRenderWidth(),renderHeight=engine.getRenderHeight(),pointerX=(event.clientX-rect.left)*renderWidth/rect.width,pointerY=(event.clientY-rect.top)*renderHeight/rect.height,viewport=camera.viewport.toGlobal(renderWidth,renderHeight),transform=scene.getTransformMatrix();let nearest:{rank:number,distance:number}|null=null;targets.forEach((target,index)=>{const box=target.mesh.subMeshes[target.subMeshIds[0]]?.getBoundingInfo().boundingBox||target.mesh.getBoundingInfo().boundingBox,projected=B.Vector3.Project(box.centerWorld,B.Matrix.IdentityReadOnly,transform,viewport);if(projected.z<0||projected.z>1)return;const distance=Math.hypot(projected.x-pointerX,projected.y-pointerY);if(!nearest||distance<nearest.distance)nearest={rank:index%30+1,distance}});const maxDistance=Math.max(90,Math.min(renderWidth,renderHeight)*.2);if(nearest&&nearest.distance<=maxDistance){lastSelection=performance.now();onSelect(nearest.rank)}};surface.addEventListener('pointerdown',selectProjectedBillboard,{capture:true});
    const selectWithRenderRay=(event:PointerEvent)=>{const rect=surface.getBoundingClientRect(),x=(event.clientX-rect.left)*engine.getRenderWidth()/rect.width,y=(event.clientY-rect.top)*engine.getRenderHeight()/rect.height,hits=scene.multiPick(x,y,candidate=>Boolean(candidate.metadata?.rankBySubMesh))||[];for(const hit of hits){const mesh=hit.pickedMesh,rank=mesh&&(mesh.metadata?.rankBySubMesh?.[hit.subMeshId]||mesh.metadata?.rankBySubMesh?.[(mesh.subMeshes[hit.subMeshId] as any)?._id]||Object.values(mesh.metadata?.rankBySubMesh||{})[0]);if(rank){lastSelection=performance.now();onSelect(Number(rank));return}}};surface.addEventListener('pointerdown',selectWithRenderRay,{capture:true});
    imported.meshes.forEach(mesh=>{mesh.isPickable=false});const hitboxMaterial=new B.StandardMaterial('billboard_hitbox_material',scene);hitboxMaterial.alpha=.001;hitboxMaterial.disableLighting=true;targets.forEach((target,index)=>{const rank=index+1,boxes=target.surfaces.map(surface=>surface.getBoundingInfo().boundingBox),minimum=boxes.reduce((value,box)=>B.Vector3.Minimize(value,box.minimumWorld),boxes[0].minimumWorld.clone()),maximum=boxes.reduce((value,box)=>B.Vector3.Maximize(value,box.maximumWorld),boxes[0].maximumWorld.clone()),size=maximum.subtract(minimum),center=minimum.add(maximum).scale(.5),minimumThickness=Math.max(radius*.00035,.01),hitbox=B.MeshBuilder.CreateBox(`billboard_hitbox_${rank}`,{width:Math.max(size.x,minimumThickness),height:Math.max(size.y,minimumThickness),depth:Math.max(size.z,minimumThickness)},scene);hitbox.position.copyFrom(center);hitbox.material=hitboxMaterial;hitbox.isPickable=true;hitbox.metadata={billboardRank:rank};hitbox.actionManager=new B.ActionManager(scene);hitbox.actionManager.registerAction(new B.ExecuteCodeAction(B.ActionManager.OnPickDownTrigger,()=>{lastSelection=performance.now();onSelect(rank)}))});scene.createOrUpdateSelectionOctree(64,2);
    scene.render();setReady(true);
  }catch(error){console.error(error);setFailed(true);}
  engine.runRenderLoop(()=>scene.render());const resize=()=>engine.resize();window.addEventListener('resize',resize);cleanup=()=>{window.clearInterval(lightingTimer);window.removeEventListener('resize',resize);surface.removeEventListener('pointerdown',beginLook,{capture:true});surface.removeEventListener('pointermove',moveLook);surface.removeEventListener('pointerup',endLook,{capture:true});surface.removeEventListener('pointercancel',endLook,{capture:true});surface.removeEventListener('click',clickFallback,{capture:true});scene.dispose();engine.dispose()};
  })();return()=>{disposed=true;cleanup()};},[onSelect]);return <div className={`babylon-stage ${ready?'scene-ready':''}`}><div className="scene-poster" aria-hidden="true"/><canvas ref={canvas} className="babylon-canvas" aria-label="Interactive 3D Times Square billboard leaderboard"/>{failed&&<a className="scene-fallback" href="/leaderboard">3D VIEW UNAVAILABLE · OPEN LEADERBOARD ↗</a>}<div className="mobile-joystick" role="group" aria-label="Walking joystick" onPointerDown={moveJoystick} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))moveJoystick(e)}} onPointerUp={stopJoystick} onPointerCancel={stopJoystick}><div className="joystick-ring"><div className="joystick-knob"/></div><span>MOVE</span></div><div className="mobile-look-hint">DRAG HERE TO TURN</div></div>}

