'use client';
import { useEffect, useRef, useState } from 'react';

type Props={onSelect:(rank:number)=>void};
const billboardNodes=['Plane.029','Plane.031','Plane.032','Plane.036','Cube.004','Cube.008','Cube.026','Cube.027','Cube.028','Cube.101','Plane.037','Cube.007','Cube.030','Cube.031','Cube.033','Cube.034','Cube.035','Cube.036','Cube.043','Cube.044','Cube.045','Cube.046','Cube.047','Cube.056','Cube.057','Cube.063','Cube.078','Cube.114','Cube.117','Cube.080'];
const billboardMaterials=new Set(['Material.039','Material.056','Material.097','Material.020','Material.024','Material.234','Material.017','Material.047','Material.049','Material.054','Material.155','Material.082','Material.093','Material.212','filename-dsc00084-jpg','Material.281','Material.119','Material.142','Material.230','Material.263','Material.269']);
const featured=[['VOIDLABS','THE FUTURE IS YOURS','#071b52','#62b8ff'],['AURORA','MAKE YOUR OWN LIGHT','#421465','#ff78e8'],['KINETIC','MOVE DIFFERENT','#cdeb34','#111111'],['NOVA.FM','HEAR THE UNHEARD','#76183f','#ff75aa'],['PIXEL.FUN','PLAY FOREVER','#9e234d','#ffc240']] as const;

export default function BabylonSquare({onSelect}:Props){const canvas=useRef<HTMLCanvasElement>(null);const [status,setStatus]=useState('Loading the Square…');const sendKey=(code:number,type:'keydown'|'keyup')=>{if(!canvas.current)return;const event=new KeyboardEvent(type,{bubbles:true});Object.defineProperty(event,'keyCode',{value:code});canvas.current.dispatchEvent(event)};useEffect(()=>{let disposed=false;let cleanup=()=>{};(async()=>{
  const B=await import('@babylonjs/core');await import('@babylonjs/loaders/glTF');if(disposed||!canvas.current)return;
  const mobile=window.matchMedia('(max-width: 850px)').matches;const engine=new B.Engine(canvas.current,true,{preserveDrawingBuffer:false,stencil:false,adaptToDeviceRatio:true});engine.setHardwareScalingLevel(mobile?1.8:window.devicePixelRatio>1.5?1.5:1);
  const scene=new B.Scene(engine);scene.clearColor=new B.Color4(.004,.007,.014,1);scene.fogMode=B.Scene.FOGMODE_EXP2;scene.fogDensity=.0035;scene.fogColor=new B.Color3(.012,.02,.035);
  const camera=new B.UniversalCamera('streetCamera',B.Vector3.Zero(),scene);camera.minZ=.04;camera.inertia=.68;camera.angularSensibility=3200;camera.keysUp=[87,38];camera.keysDown=[83,40];camera.keysLeft=[65,37];camera.keysRight=[68,39];camera.attachControl(canvas.current,true);
  const hemi=new B.HemisphericLight('night',new B.Vector3(0,1,0),scene);hemi.intensity=.72;hemi.diffuse=new B.Color3(.52,.65,.8);hemi.groundColor=new B.Color3(.08,.06,.11);
  const glow=new B.GlowLayer('billboardGlow',scene,{blurKernelSize:22});glow.intensity=.35;
  try{
    const imported=await B.SceneLoader.ImportMeshAsync('', '/models/', mobile?'timesquare-mobile.glb':'timesquare-web.glb', scene);if(disposed)return;const findImported=(name:string)=>imported.meshes.find(mesh=>mesh.name===name||mesh.id===name||mesh.name.startsWith(`${name}_`)||mesh.id.startsWith(`${name}_`));
    const roots=imported.meshes.filter(m=>!m.parent);const vectors=roots.length?roots[0].getHierarchyBoundingVectors(true):scene.getWorldExtends();const center=vectors.min.add(vectors.max).scale(.5);const extent=vectors.max.subtract(vectors.min);const radius=Math.max(extent.x,extent.y,extent.z);
    const eyeY=vectors.min.y+extent.y*.021;const marginX=extent.x*.055;const marginZ=extent.z*.12;
    camera.position.set(center.x,eyeY,center.z);camera.speed=Math.max(.08,radius*.0038);
    const area=(mesh:B.AbstractMesh)=>{const box=mesh.getBoundingInfo().boundingBox;const size=box.maximumWorld.subtract(box.minimumWorld);return Math.max(size.x*size.y,size.x*size.z,size.y*size.z)};
    const namedCandidates=billboardNodes.map(findImported).filter((mesh):mesh is B.AbstractMesh=>Boolean(mesh));const materialCandidates=imported.meshes.filter(mesh=>{const material=(mesh as B.Mesh).material;if(!material)return false;const names=[material.name,...(('subMaterials' in material)?(material.subMaterials||[]).map(item=>item?.name||''):[])];return names.some(name=>billboardMaterials.has(name))});const candidates=(namedCandidates.length>=20?namedCandidates:materialCandidates).filter((mesh,index,list)=>list.indexOf(mesh)===index).sort((a,b)=>area(b)-area(a)).slice(0,30);
    const topFive=candidates.slice(0,5);const topCenter=topFive.reduce((sum,mesh)=>sum.add(mesh.getBoundingInfo().boundingBox.centerWorld),B.Vector3.Zero()).scale(1/Math.max(1,topFive.length));camera.setTarget(new B.Vector3(topCenter.x,Math.max(eyeY+extent.y*.07,topCenter.y),topCenter.z));
    topFive.forEach((mesh,index)=>{const [name,tag,bg,fg]=featured[index];mesh.metadata={...(mesh.metadata||{}),rank:index+1};mesh.isPickable=true;
      const tex=new B.DynamicTexture(`featured_${index+1}`,{width:1024,height:512},scene,false);const ctx=tex.getContext();ctx.fillStyle=bg;ctx.fillRect(0,0,1024,512);ctx.strokeStyle=fg;ctx.lineWidth=18;ctx.strokeRect(18,18,988,476);ctx.fillStyle=fg;ctx.textAlign='right';ctx.font='900 105px Arial';ctx.fillText(`#${index+1}`,955,125);ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font='900 120px Arial';ctx.fillText(name,512,310);ctx.font='bold 28px monospace';ctx.fillText(tag,512,385);ctx.fillStyle=fg;ctx.font='900 30px monospace';ctx.fillText('CLICK TO OUTBID',512,450);tex.update();const bm=new B.StandardMaterial(`featured_material_${index+1}`,scene);bm.diffuseTexture=tex;bm.emissiveTexture=tex;bm.emissiveColor=B.Color3.White();bm.disableLighting=true;bm.backFaceCulling=false;mesh.material=bm;
    });
    candidates.slice(5).forEach((mesh,index)=>{const rank=index+6;mesh.metadata={...(mesh.metadata||{}),rank};mesh.isPickable=true;const hue=(rank*37)%360;const tex=new B.DynamicTexture(`ranked_billboard_${rank}`,{width:1024,height:512},scene,false);const ctx=tex.getContext();ctx.fillStyle=`hsl(${hue} 55% 18%)`;ctx.fillRect(0,0,1024,512);ctx.strokeStyle='#d7ff35';ctx.lineWidth=18;ctx.strokeRect(18,18,988,476);ctx.fillStyle='#d7ff35';ctx.textAlign='right';ctx.font='900 105px Arial';ctx.fillText(`#${rank}`,955,125);ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font='900 76px Arial';ctx.fillText('TIMESQUARES.LOL',512,310);ctx.fillStyle='#d7ff35';ctx.font='900 32px monospace';ctx.fillText('CLICK TO OUTBID',512,425);tex.update();const mat=new B.StandardMaterial(`ranked_material_${rank}`,scene);mat.diffuseTexture=tex;mat.emissiveTexture=tex;mat.disableLighting=true;mat.backFaceCulling=false;mesh.material=mat;});
    const yearParts=['Cube.082','Cube.083','Cube.084','Cube.085','Cube.086','Cube.087'].map(findImported).filter((mesh):mesh is B.AbstractMesh=>Boolean(mesh));const yearAnchor=yearParts[0];if(yearAnchor){const box=yearAnchor.getBoundingInfo().boundingBox;const size=box.maximumWorld.subtract(box.minimumWorld);const yearSign=B.MeshBuilder.CreatePlane('year_2026',{width:Math.max(size.x,size.z)*1.06,height:size.y*1.06,sideOrientation:B.Mesh.DOUBLESIDE},scene);yearSign.position.copyFrom(box.centerWorld);yearSign.rotationQuaternion=yearAnchor.absoluteRotationQuaternion?.clone()||B.Quaternion.Identity();yearSign.isPickable=false;yearParts.forEach(mesh=>mesh.setEnabled(false));const yearTex=new B.DynamicTexture('year_2026_texture',{width:512,height:768},scene,false);const yearCtx=yearTex.getContext();yearCtx.fillStyle='#101417';yearCtx.fillRect(0,0,512,768);yearCtx.strokeStyle='#ff4d2e';yearCtx.lineWidth=22;yearCtx.strokeRect(12,12,488,744);yearCtx.fillStyle='#ff4d2e';yearCtx.textAlign='center';yearCtx.font='900 150px Arial';yearCtx.fillText('2026',256,440);yearTex.update();const yearMat=new B.StandardMaterial('year_2026_material',scene);yearMat.diffuseTexture=yearTex;yearMat.emissiveTexture=yearTex;yearMat.disableLighting=true;yearMat.backFaceCulling=false;yearSign.material=yearMat;}
    scene.onBeforeRenderObservable.add(()=>{camera.position.x=Math.min(vectors.max.x-marginX,Math.max(vectors.min.x+marginX,camera.position.x));camera.position.z=Math.min(vectors.max.z-marginZ,Math.max(vectors.min.z+marginZ,camera.position.z));camera.position.y=eyeY;camera.cameraDirection.y=0;});
    scene.onPointerObservable.add(info=>{if(info.type===B.PointerEventTypes.POINTERPICK){let mesh=info.pickInfo?.pickedMesh;while(mesh&&!mesh.metadata?.rank)mesh=mesh.parent as B.AbstractMesh|null;if(mesh?.metadata?.rank)onSelect(mesh.metadata.rank)}});
    setStatus('');
  }catch(error){console.error(error);setStatus('3D scene unavailable — open the leaderboard');}
  engine.runRenderLoop(()=>scene.render());const resize=()=>engine.resize();window.addEventListener('resize',resize);cleanup=()=>{window.removeEventListener('resize',resize);scene.dispose();engine.dispose()};
  })();return()=>{disposed=true;cleanup()};},[onSelect]);const control=(code:number,label:string,symbol:string)=><button aria-label={label} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);sendKey(code,'keydown')}} onPointerUp={()=>sendKey(code,'keyup')} onPointerCancel={()=>sendKey(code,'keyup')}>{symbol}</button>;return <div className="babylon-stage"><canvas ref={canvas} className="babylon-canvas" aria-label="Interactive 3D Times Square billboard leaderboard"/><div className="mobile-walk" aria-label="Walking controls">{control(38,'Walk forward','▲')}<div>{control(37,'Move left','◀')}{control(40,'Walk backward','▼')}{control(39,'Move right','▶')}</div><span>DRAG TO LOOK</span></div>{status&&<div className="scene-loading" role="status"><div className="load-skyline"><i/><i/><i/><i/><i/></div><strong>TIMESQUARES<span>.LOL</span></strong><small>{status}</small><em>30 LIVE BILLBOARDS · ENTERING BROADWAY</em></div>}</div>}
