import type {Metadata} from 'next';import {PublicFooter,PublicNav} from '../PublicChrome';import {LEGAL_VERSIONS,legalConfig} from '../../lib/legal';
/** ATTORNEY REVIEW REQUIRED: This legal draft is not represented as counsel-approved. */
export const metadata:Metadata={title:'Terms & Conditions | Timesquares.lol',description:'Terms governing Timesquares.lol virtual advertising, bidding, payments, and Real Times Square rewards.'};
const sections=[
['Platform Description',<>Timesquares.lol operates a competitive digital advertising platform. Advertisers may pay to obtain or improve virtual billboard ranking and placement. Positions can change when another advertiser submits and successfully pays a qualifying higher bid. The current 2D ranking and platform database are authoritative if a 3D view is delayed or unavailable.</>],
['No Permanent Billboard Ownership',<>You do not purchase, own, lease, or acquire a property interest in a virtual or physical billboard. A payment purchases the platform participation, placement, or related service described at checkout. Virtual positions may change under the ranking rules.</>],
['Bidding',<>The interface displays applicable minimums and projected positions. Bid increments, placement logic, and availability may vary by position or program version. A bid affects ranking only after confirmed successful payment. Paid bids are generally final except where these Terms, mandatory law, or a written refund policy states otherwise. We may correct clear technical, pricing, ranking, or attribution errors and will use reasonable measures to avoid unfairly disadvantaging affected advertisers.</>],
['Payments, Taxes, Refunds, and Disputes',<>You authorize Timesquares and its payment processor to charge the amount shown at checkout. Failed or unconfirmed payments do not activate a bid. You are responsible for applicable taxes unless collected at checkout. Refunds are not guaranteed and may affect qualifying reward spend. Disputes, reversals, fraud, and chargebacks may suspend an account, remove a placement, place an unfulfilled reward under review, or cancel eligibility where permitted by the applicable reward terms and law.</>],
['Advertising Content and Rights',<>You represent that you own or have sufficient permission and licenses for every submitted image, logo, trademark, video, statement, likeness, link, and other material. Content must not be illegal, infringing, deceptive, malicious, or prohibited by the <a href="/advertising-rules">Advertising Rules</a>. Advertisers remain responsible for claims and required disclosures.</>],
['Creative Moderation',<>Timesquares may approve, reject, disable, or remove content that violates law, these Terms, platform rules, security requirements, or fulfillment-provider standards. Payment and virtual ranking do not guarantee acceptance for physical fulfillment. Where appropriate, an advertiser may submit a compliant replacement creative.</>],
['Real Times Square Rewards',<>Qualifying advertisers may become eligible for promotional real-world advertising rewards. An advertised threshold may currently be $750, but eligibility, package details, repeat availability, expiration, transferability, and remedies are governed by the reward configuration and program version in effect when the reward is earned. Virtual Timesquares.lol placement is separate from physical Times Square advertising. Virtual rank does not determine or promise a particular physical screen, building, or position.</>],
['Third-Party Fulfillment',<>Independent billboard owners, operators, agencies, and media providers may fulfill physical rewards. Placements remain subject to inventory availability, provider approval, technical specifications, content rules, scheduling, maintenance, outages, local restrictions, and other provider requirements. No specific physical screen is guaranteed unless expressly confirmed in writing.</>],
['Scheduling and Rush Requests',<>Preferred dates are requests only. A placement is not scheduled until Timesquares confirms it. Minimum lead times may apply. Rush fulfillment is not guaranteed and may require separate approval or fees. Confirmed dates may still change for provider, inventory, safety, legal, maintenance, or technical reasons.</>],
['Physical Creative Approval',<>A physical creative must satisfy both Timesquares rules and the applicable provider’s rules. Provider rejection does not permit an advertiser to bypass those requirements. Timesquares may request revisions or a replacement file before booking.</>],
['Reward Availability and Remedies',<>If a provider or screen becomes unavailable, ceases operations, changes inventory or pricing, or experiences a technical failure, Timesquares may—where consistent with the applicable earned program version—reschedule, use comparable Times Square inventory, use an alternate provider, or offer an equivalent replacement reward. Unless expressly stated otherwise, rewards have no cash redemption value.</>],
['Transferability and Expiration',<>Rewards are {legalConfig.rewardsTransferable?'transferable only under the current configured program rules':'non-transferable unless Timesquares approves a transfer in writing'}. {legalConfig.rewardExpirationDays>0?`The current configured claim period is ${legalConfig.rewardExpirationDays} days, and the applicable expiration will be disclosed when earned and during claim.`:'No automatic expiration period is currently configured. Timesquares will not silently expire an earned reward; any future period must be disclosed when earned and during claim.'}</>],
['Refunds, Chargebacks, and Rewards',<>Virtual platform purchases and promotional real-world rewards are separate. A refund, dispute, reversal, or chargeback of qualifying payments may reduce qualifying spend and place an unfulfilled reward under review or result in cancellation under the applicable program version. Historical ledger entries are retained rather than silently deleted.</>],
['Proof of Placement',<>Timesquares may provide available photographs, video, provider confirmation, timestamps, screenshots, links, or other evidence. Professional photography or video is not guaranteed unless expressly included in the reward package in effect when earned.</>],
['Intellectual Property License',<>You retain ownership of your creative. You grant Timesquares a worldwide, non-exclusive, royalty-free license, for the duration reasonably needed to operate and promote the service, to host, reproduce, display, resize, crop, format, transmit to fulfillment providers, publicly display within Timesquares, physically display through approved providers, and create necessary campaign proof or share assets. This license is limited to operating, fulfilling, documenting, and promoting Timesquares and your campaign.</>],
['Public Display',<>Advertisements are publicly displayed and may be photographed, recorded, indexed, reposted, or discussed by third parties. Timesquares cannot control independent third-party capture or commentary.</>],
['Analytics and Outcomes',<>Impressions, clicks, click-through rates, traffic sources, rankings, and estimated physical reach may be estimates, sampled, delayed, or supplied by third parties. Timesquares does not guarantee traffic, sales, leads, conversions, publicity, or any business result.</>],
['Platform Availability',<>The service may experience maintenance, downtime, ranking delays, payment delays, data-processing issues, network failures, or 3D rendering failures. Timesquares may modify or discontinue non-earned features prospectively. Where views conflict, authoritative platform records control.</>],
['Suspension and Termination',<>Timesquares may restrict or suspend accounts for suspected fraud, chargebacks, abuse, malicious destinations, prohibited content, ranking manipulation, security threats, or violation of these Terms. We may preserve records reasonably required for fraud prevention, disputes, accounting, and legal compliance.</>],
['Disclaimer of Warranties',<>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE PLATFORM AND REWARDS ARE PROVIDED “AS IS” AND “AS AVAILABLE,” WITHOUT WARRANTIES NOT EXPRESSLY STATED IN WRITING. Nothing in these Terms limits non-waivable consumer rights.</>],
['Limitation of Liability',<>TO THE MAXIMUM EXTENT PERMITTED BY LAW, TIMESQUARES WILL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR LOST PROFITS, REVENUE, DATA, GOODWILL, OR OPPORTUNITIES, subject to applicable law and any non-waivable rights.</>],
['Indemnification',<>You agree to defend, indemnify, and hold harmless Timesquares and its personnel from third-party claims arising from your advertising content, destinations, unlawful or misleading claims, infringement, misuse of likeness, or material breach of these Terms, subject to applicable law.</>],
['Governing Law',<>The governing jurisdiction is <strong>{legalConfig.governingState}</strong>, subject to any mandatory rights or rules that apply in your location.</>],
['Changes to Terms',<>Timesquares may update these Terms prospectively and will post an updated version and effective date. Material changes affecting an already-earned physical reward will be handled under the applicable reward-program version unless mandatory law requires otherwise.</>],
['Contact',<>Support: <strong>{legalConfig.supportEmail}</strong><br/>Legal notices: <strong>{legalConfig.legalEmail}</strong></>]
] as const;
export default function Terms(){return <main className="legal-page"><PublicNav/><header><p>LEGAL</p><h1>TERMS &amp;<br/>CONDITIONS</h1><span>Version {LEGAL_VERSIONS.terms}</span></header><div className="legal-layout"><aside>{sections.map(([title])=><a key={title} href={`#${title.toLowerCase().replace(/[^a-z]+/g,'-')}`}>{title}</a>)}</aside><article>{sections.map(([title,body])=><section key={title} id={title.toLowerCase().replace(/[^a-z]+/g,'-')}><h2>{title}</h2><p>{body}</p></section>)}</article></div><PublicFooter/></main>}

