import {env} from 'cloudflare:workers';
import {clerkEmail,verifyClerkRequest} from '../../../../lib/clerk';
import {LEGAL_VERSIONS} from '../../../../lib/legal';
import {REAL_BILLBOARD_DEFAULTS} from '../../../../lib/real-billboard';
const slugify=(value:string)=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,48)||'campaign';
export async function GET(request:Request){const user=await verifyClerkRequest(request);if(!user)return Response.json({campaigns:[]});const rows=await env.DB.prepare('SELECT * FROM real_billboard_campaigns WHERE user_id=? ORDER BY created_at DESC').bind(user.sub).all();return Response.json({campaigns:rows.results})}
export async function POST(request:Request){const user=await verifyClerkRequest(request);if(!user)return Response.json({error:'Sign in to book Billboard #49.'},{status:401});const body=await request.json() as Record<string,any>;if(!body.advertiserName||!body.preferredDate1)return Response.json({error:'Add your advertiser name and preferred date.'},{status:400});if(!body.acceptTerms||!body.acceptPackageTerms||!body.acceptRules)return Response.json({error:'Accept all three agreements to continue.'},{status:428});
 const price=Number((await env.DB.prepare("SELECT value FROM platform_settings WHERE key='real_billboard_sale_price_cents'").first<{value:string}>())?.value||REAL_BILLBOARD_DEFAULTS.priceCents),apiKey=process.env.DODO_PAYMENTS_API_KEY,productId=process.env.DODO_REAL_TIMES_SQUARE_PRODUCT_ID;if(!apiKey||!productId)return Response.json({error:'The Billboard #49 checkout product still needs to be configured.'},{status:503});const id=crypto.randomUUID(),now=new Date().toISOString(),base=slugify(body.advertiserName),slug=`${base}-${id.slice(0,6)}`,email=await clerkEmail(user.sub);
 await env.DB.batch([env.DB.prepare(`INSERT INTO real_billboard_campaigns (id,slug,user_id,advertiser_name,advertiser_email,website,social_links_json,status,preferred_date_1,preferred_date_2,preferred_date_3,timezone,duration_seconds,creative_file_url,creative_headline,sale_price_cents,terms_version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,slug,user.sub,body.advertiserName,email,body.website||null,JSON.stringify(body.socialLinks||{}),'pending_payment',body.preferredDate1,body.preferredDate2||null,body.preferredDate3||null,'America/New_York',15,body.creativeFileUrl||null,body.creativeHeadline||null,price,LEGAL_VERSIONS.real_times_square_package_terms,now,now),...(['terms','real_times_square_package_terms','advertising_rules'] as const).map(type=>env.DB.prepare('INSERT OR IGNORE INTO terms_acceptances (id,user_id,terms_type,version,accepted_at) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),user.sub,type,LEGAL_VERSIONS[type],now))]);
 const origin=new URL(request.url).origin,checkout=await fetch(`${process.env.DODO_PAYMENTS_API_BASE||'https://live.dodopayments.com'}/checkouts`,{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({product_cart:[{product_id:productId,quantity:1,amount:price}],customer:email?{email}:{},return_url:`${origin}/dashboard?real-times-square=paid`,cancel_url:`${origin}/real-times-square/book`,metadata:{purchase_type:'real_billboard_49',campaign_id:id,clerk_user_id:user.sub}})}),result=await checkout.json() as any;if(!checkout.ok||!result.checkout_url)return Response.json({error:result.message||'Unable to start checkout.'},{status:502});await env.DB.prepare('UPDATE real_billboard_campaigns SET checkout_session_id=? WHERE id=?').bind(result.session_id||null,id).run();return Response.json({url:result.checkout_url})}
