import {env} from 'cloudflare:workers';
import {verifyClerkRequest} from '../../../lib/clerk';
const create=`CREATE TABLE IF NOT EXISTS advertiser_profile_links (user_id TEXT PRIMARY KEY, slug TEXT NOT NULL UNIQUE, display_name TEXT NOT NULL, bio TEXT, website TEXT, x_url TEXT, instagram_url TEXT, linkedin_url TEXT, youtube_url TEXT, tiktok_url TEXT, updated_at TEXT NOT NULL)`;
const clean=(value:unknown)=>String(value||'').trim().slice(0,500);
const safeUrl=(value:unknown)=>{const text=clean(value);if(!text)return '';try{const url=new URL(text);return ['http:','https:'].includes(url.protocol)?url.toString():''}catch{return ''}};
const slugify=(value:string,userId:string)=>`${value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,42)||'advertiser'}-${userId.slice(-6).toLowerCase()}`;
const output=(row:Record<string,any>)=>({slug:row.slug||'',displayName:row.display_name||'',bio:row.bio||'',website:row.website||'',xUrl:row.x_url||'',instagramUrl:row.instagram_url||'',linkedinUrl:row.linkedin_url||'',youtubeUrl:row.youtube_url||'',tiktokUrl:row.tiktok_url||''});
export async function GET(request:Request){const user=await verifyClerkRequest(request);if(!user)return Response.json({error:'Unauthorized'},{status:401});await env.DB.prepare(create).run();const row=await env.DB.prepare('SELECT * FROM advertiser_profile_links WHERE user_id=?').bind(user.sub).first<Record<string,any>>();return Response.json(row?output(row):{})}
export async function POST(request:Request){const user=await verifyClerkRequest(request);if(!user)return Response.json({error:'Unauthorized'},{status:401});const body=await request.json() as Record<string,unknown>,displayName=clean(body.displayName).slice(0,80);if(!displayName)return Response.json({error:'Display name is required.'},{status:400});const values={slug:slugify(displayName,user.sub),displayName,bio:clean(body.bio).slice(0,240),website:safeUrl(body.website),xUrl:safeUrl(body.xUrl),instagramUrl:safeUrl(body.instagramUrl),linkedinUrl:safeUrl(body.linkedinUrl),youtubeUrl:safeUrl(body.youtubeUrl),tiktokUrl:safeUrl(body.tiktokUrl)};await env.DB.prepare(create).run();await env.DB.prepare(`INSERT INTO advertiser_profile_links (user_id,slug,display_name,bio,website,x_url,instagram_url,linkedin_url,youtube_url,tiktok_url,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET slug=excluded.slug,display_name=excluded.display_name,bio=excluded.bio,website=excluded.website,x_url=excluded.x_url,instagram_url=excluded.instagram_url,linkedin_url=excluded.linkedin_url,youtube_url=excluded.youtube_url,tiktok_url=excluded.tiktok_url,updated_at=excluded.updated_at`).bind(user.sub,values.slug,values.displayName,values.bio,values.website,values.xUrl,values.instagramUrl,values.linkedinUrl,values.youtubeUrl,values.tiktokUrl,new Date().toISOString()).run();return Response.json(values)}

